### ISSUE TITLE
Serving the react-app should support routing

### ISSUE THREAD

**Issue by wendrul** [wendrul/ft_transcendence#1]
On the `create-react-app` documentation, in the secion about [deployment](https://create-react-app.dev/docs/deployment/#serving-apps-with-client-side-routing):

> If you use routers that use the HTML5 [pushState history API](https://developer.mozilla.org/en-US/docs/Web/API/History_API#Adding_and_modifying_history_entries) under the hood (for example, [React Router](https://github.com/ReactTraining/react-router) with browserHistory), many static file servers will fail.

Currently, the production build is using `serve -s build` to serve the app. This should be done properly.

**Comment by christie26** [comment]
hello! I enjoy your game!!

**Comment by wendrul** [comment]
@christie26 duplicate of #545
